fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    cron: "https://github.com/puppetlabs/puppetlabs-cron_core.git"
  symlinks:
    logrotate: "#{source_dir}"
